### PR TITLE
Fix Phpstan issues

### PR DESCRIPTION
**Pull request by BushraAsif**

### CODE REVIEW

**Review by shahbaz-mehar — COMMENTED** [review]
Changes have been reviewed.

**Comment by emicha** [comment]
@BushraAsif Missing release notes.

**Comment by emicha** [comment]
@BushraAsif Missing release notes.

**Comment by BushraAsif** [comment]
> @BushraAsif Missing release notes.

@emicha, the change is related to phpstan, we didn't make any functional changes.

**Review by emicha — APPROVED** [review]

**Pull request merged**
